In [1]:
## 0.0 pytorch fundamentals 

In [2]:
import torch
print(torch.__version__)


2.7.1+cu128


In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


## Introduction to tensors

In [4]:
#scalar -- way to create a tensor 
scalar = torch.tensor(7)
scalar


tensor(7)

In [5]:
scalar.ndim

0

In [6]:
## get tensor back as python int 
scalar.item()

7

In [7]:
#vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape


torch.Size([2])

In [10]:
#matrix 
MATRIX =torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
#finding number of dimensions 
MATRIX.ndim

2

In [12]:
#accessing the matrix of certain dimensions in the below its of 1st demensions 
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX =torch.tensor([[[[7,8,9,10],[5,8,9,10],[1,2,3,4],[5,6,7,8]]]])
MATRIX

tensor([[[[ 7,  8,  9, 10],
          [ 5,  8,  9, 10],
          [ 1,  2,  3,  4],
          [ 5,  6,  7,  8]]]])

In [14]:

MATRIX.shape

torch.Size([1, 1, 4, 4])

### Random Tensors

why random tensors?
Random tensors are important because the way many neural networks learns is that thwy start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with the random numbers-> look at data ->update random numbers ->look at data ->update data `

In [15]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7275, 0.0604, 0.2719, 0.9009],
        [0.7484, 0.6105, 0.3863, 0.1812],
        [0.8563, 0.3188, 0.8284, 0.8082]])

In [16]:
#creating a random tensor with similar shape to an image tensor 
random_image_size_tensor = torch.rand(size =(3,224,224))   # colour channels (R,G,B),height,width
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones


In [17]:
#create a tensorr of all zeros 
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
#create a tensorr of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
#checking data types
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like 

In [20]:
#use torch.arange()
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
#creating a tensor like 
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors Datatype

Note: Tensor datatypes is one of the 3 big errors you'll run into with pytorch & deep learning:
1. Tensor not right datatype 
2. Tensors not right shape 
3. Tensors not on the right device 


In [22]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None, #what datatypes is the tensor (e.g float 32 or float 16) 
device=None,#what device is your tensor on 
requires_grad=False) #whether or not to track gradients with this tensors operations 
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors 

1. Tensorsnot right datatype - to do get datatype from tensor, can use tensor.dtype
 2. Tensors not right shape -to get shape from a tensor, can use tensor.shape
 3. Tensors not on the right device - to get devices from a tensor,can use tensor.device

In [26]:
# Create a tensor 
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2538, 0.0328, 0.8857, 0.8756],
        [0.7874, 0.8154, 0.9445, 0.5359],
        [0.7752, 0.8236, 0.5989, 0.6728]])

In [27]:
#find out the details about some tensors 
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.2538, 0.0328, 0.8857, 0.8756],
        [0.7874, 0.8154, 0.9445, 0.5359],
        [0.7752, 0.8236, 0.5989, 0.6728]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors(tensors operations)
Tensor operations include :
* Addition
* Subtraction
* Multiplication (element-wise)
* Division 
* Matrix Multipklication 

In [28]:
# create  a tensor and adding 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [29]:
# multiplying tensor by 10
tensor *10

tensor([10, 20, 30])

In [30]:
tensor

tensor([1, 2, 3])

In [31]:
#subtract 10
tensor - 10

tensor([-9, -8, -7])

In [32]:
# Try pytorch in-built Functions
torch.add(tensor,10) 

tensor([11, 12, 13])

### Matric Multiplications

Two main ways of performing Multiplications in neural networks and deep learning:

1. Element-Wise Multiplication 
2. Matrix Multiplication (dot product)

`matrix multiplication has same rules of mathematics`


In [33]:
#Element wise multiplication 
print(tensor, "*", tensor )
print(f"Equals:{tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [34]:
# matrix multiplications 
torch.matmul(tensor,tensor)

tensor(14)

In [35]:
tensor1= torch.tensor([[1,2],[2,3]])
tensor1


tensor([[1, 2],
        [2, 3]])

In [36]:
tensor2= torch.tensor([[5,2],[5,3]])
tensor2

tensor([[5, 2],
        [5, 3]])

In [37]:
torch.matmul(tensor1,tensor2)

tensor([[15,  8],
        [25, 13]])

In [38]:
%%time 
value = 0
for i in range(len(tensor)):
    value+= tensor[i]* tensor[i]
    print(value)

tensor(1)
tensor(5)
tensor(14)
CPU times: total: 0 ns
Wall time: 3.32 ms


In [39]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 72.7 μs


tensor(14)

In [40]:
#shapes for matrix Multiplications
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

### torch.matmul(tensor_A,tensor_B) 
 This code will give error as it doesnt satisfies the matrix multipication dimensions rules and 3*2 and 3*2 cannot be multiplied 
there is one solution for this which is transpose of a matrix and after which it will allow us to perform the oprations 

In [41]:
#how to do transpose of a matrix
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [42]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [43]:
torch.matmul(tensor_B.T,tensor_A)


tensor([[ 76, 100],
        [103, 136]])

### Finding the min,max,mean,sum etc (tensor aggregation)

In [44]:
# create a tensor 
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
#find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [46]:
#find mean - the mean should always be float so type casted of  form int to float32
torch.mean(x.type(torch.float32))  ,   x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

### Finding the Positional Min and Max

In [47]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
# Finding the position in tensor that has the minimum value - > returns the index of minimum 
x.argmin()

tensor(0)

In [49]:
# Finding the position in tensor that has the maximum value - > returns the index of maximum
x.argmax()

tensor(9)

## Reshaping , Stacking, Squeezing and unsqueezing tensors

* Reshaping- reshapes an input tensor to a defined shape
* view - return a view of an input tensor of certain shape but keep the same memory as the original tensor 
* stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all the `1` dimensions from a tensor 
* Unsqueeze - add a `1` dimension to the target tensor 
* permute - Return a view of the input with dimensions permuted (swaped) in a certain way

In [50]:
#  Let's create a tensor 
x= torch.arange(1.,10.)
x,x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [51]:
# Adding an extra dimensions 
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
# change the view 
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input )
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [54]:
# Stack tensor on top of each other 
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
# torch.squeeze()- removes all ths single dimensions from a target tensor
print (f"prevoious tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

#remove extra dimensions from x_shaped
x_squeezed = x_reshaped.squeeze()
print (f"\n New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

prevoious tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape: torch.Size([1, 9])

 New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [56]:
# torch.unsqueeze()- adds a single dimensions to a target tensor at a specific dim(dimensions )
print (f"prevoious target: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")

#remove extra dimensions from x_shaped
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print (f"\n New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

prevoious target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

 New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [57]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order 
X_original = torch.rand(size=(224,224,3)) #[height,width, colour_channels]

#permute the original tensors to rearrange the axis(or dim ) order 
x_permuted = X_original.permute(2,0,1) #shifts axis 0->1,1->2, 2->0

print(f"previous shape: {X_original.shape}")
print(f"New shape: {x_permuted.shape}")

previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### indexing(selecting data from tensors)

Indexing with pytorch is similar to indexing with numpy


In [62]:
#create a tensor 
x= torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [63]:
#Lets index in our new tensor 
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Lets index on middle bracket(dim = 1) (i.e it will target row in simple languages )
x[0][0]

#we can also do this using x[0,0]

tensor([1, 2, 3])

In [ ]:
#lets index on the most inner bracket(last dimensions)(i.e it will target the elements)
x[0,0,2]

tensor(3)

In [69]:
# you can also use ":" to select ""all"" of a target dimensions 
x[:,0]

tensor([[1, 2, 3]])

In [70]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimensions 
x[:,:,1]

tensor([[2, 5, 8]])

In [71]:
# get all the values of the 0 dimension but only the 1 index value of 1st and 2nd dimensions 
x[:,1,1]

tensor([5])

In [72]:
# get index 0 of 0th and 1st dimensions and all values of 2nd dimensions 
x[0,0,:]

tensor([1, 2, 3])

In [76]:
# Index on x to return 9
x[0,2,2]

tensor(9)

In [78]:
#index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])